version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO web console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
  smb:
    image: dperson/samba
    container_name: test_smb
    volumes:
      - ./smbdata:/mount/data
    command: >
      -u "testuser;testpass" 
      -s "share;/mount/data;yes;no;yes;all;none"
    restart: unless-stopped
  
  jupy:
    image: quay.io/jeremyyg1996/jupy:0.1
    container_name: jupy
    ports:
      - "8888:8888"  # Jupyter Notebook
    volumes:
      - ./scripts:/home/jovyan/scripts  # Mount local 'scripts' folder into the container
      - ./data:/home/jovyan/data  # Mount local 'data' folder into the container
volumes:
  minio-data: