version: '3.8'

services:
  smb_sync:
    image: python-with-smb-lib:latest
    container_name: smb_sync
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
    working_dir: /app
    command: python ./scripts/transfer.py
